#! /usr/bin/env node
import inquirer from "inquirer";
// computer will generate a random number
// user input for guessing
//compare number generated by computer with user input than give output as user wins or lose
const randomNumber = Math.floor(Math.random() * 10 + 1);
const answer = await inquirer.prompt([
    {
        message: "Guess number between 1 and 10 : ",
        type: "number",
        name: "userNum",
    },
]);
if (answer.userNum === randomNumber) {
    console.log("Congratulations! your guess is right");
}
else {
    console.log(`${"Oops! your guess is wrong  the number was  "}${randomNumber}`);
}
